---
title: "Pain Research - Dr. Marc O. Martel"
author: "Jiaqi Bi"
date: "2023-07-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Two different files
#setwd("~/Desktop/Project; Daily diaries; 30-days/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Martel")
#setwd("~/Desktop/Project; Daily diaries; 30-days/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Jamison")
```

```{r}
## Load packages
library(tidyverse)
library(ggplot2)
library(tidyr)
library(haven)## This library provides functions to read sav file into R
library(lme4)
library(lmerTest)
```

```{r}
## Baseline data
#df1 <- read_sav("~/Desktop/Project; Daily diaries; 30-days/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Jamison/Dataset; Jamison project; Baseline.sav")
df1 <- read_sav("E:/UWO/DR Marc O Martel data/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Jamison/Dataset; Jamison project; Baseline.sav")
## Daily data
#df2 <- read_sav("~/Desktop/Project; Daily diaries; 30-days/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Jamison/Dataset; Jamison project; Daily.sav")
df2 <- read_sav("E:/UWO/DR Marc O Martel data/Pain-Research-1-Dr-Marc-O-Martel/Datasets; Project; Jamison/Dataset; Jamison project; Daily.sav")



## Examine the duplicated observation
df1$ID[which(duplicated(df1$ID))]
df2$StudyID[which(duplicated(df2$StudyID))]

df1 <- df1 |>
  filter(!duplicated(ID))
df2 <- df2 |>
  filter(!duplicated(StudyID)) |>
  rename(ID = StudyID)

## Time variable to numerical day (consecutive)
date_cols <- grep("^Date", names(df2), value = TRUE)

df2 <- df2 %>%
  mutate(across(all_of(date_cols), as.Date, format = "%Y-%m-%d"))

## Correct abberrant years
df2 <- df2 %>%
  rowwise() %>%
  mutate(across(all_of(date_cols), ~ {
    if (. != Date1 && !is.na(.)) {
      day_diff <- as.numeric(. - Date1)
      if (day_diff < 0) {
        update(., year = year(Date1))
      } else {
        .
      }
    } else {
      .
    }
  })) %>%
  ungroup()

####### Below investigates the rest of aberrant objects #######
##### Above does not solve those entering a new year ##########
df2_investigate <- df2 |>
  pivot_longer(
  cols = starts_with("Date"), 
  names_to = "Date_Number", 
  values_to = "Date_Value"
) |>
  select(ID, Date_Value)

print(n = 36, df2_investigate[df2_investigate$ID == 673,])
###############################################################

## Below solved all objects date problem
df2$Date8[df2$ID == 610] <- "2023-01-01"
df2$Date8[df2$ID == 703] <- "2022-01-09"
df2$Date8[df2$ID == 741] <- "2021-01-10"
df2$Date8[df2$ID == 680] <- "2023-01-09"
df2$Date28[df2$ID == 673] <- "2023-02-02"

## Convert the date to number
df2 <- df2 |>
  mutate(across(all_of(date_cols[-1]), ~ as.numeric(. - df2$Date1 + 1)))

df2$Date1 <- 1
all_cols <- names(df2)

#for (i in 2:length(date_cols)) {
#  if (any(df2[[date_cols[i]]] == 1, na.rm = TRUE)) {
#    same_day_cols <- grep(paste0("_", i), all_cols, value = TRUE)
#    df2[df2[[date_cols[i]]] == 1 & !is.na(df2_test[[date_cols[i]]]), same_day_cols] <- NA
#  }
#}

## Wide to long
df2_long <- df2 |>
  pivot_longer(cols = -ID,
               names_to = c(".value", "day"),
               names_pattern = "([A-Za-z]+)(\\d+)") |>
  select(-day) |>
  rename(Day = Date) |>
  filter(Day <= 30 & !is.na(Day)) |>
  group_by(ID) |>
  distinct(Day, .keep_all = TRUE) |>
  complete(Day = seq(1,30))

## replace all -1 to NA
df2_long <- df2_long |>
  mutate_all(~if_else(. < 0, NA_real_, .))

df2_long <- df2_long |>
  rename(GlobalImprovement = Changed)

## Calculate the lagged variable
df2_long <- df2_long |>
  group_by(ID) |>
  arrange(ID, Day) |>
  mutate(AvePain_Change = AvePain - lag(AvePain), 
         ActivityInt_Change = ActivityInt - lag(ActivityInt), 
         Mood_Change = Mood - lag(Mood)) 

df2_greaterthan7 <- df2_long |>
  group_by(ID) %>%
  summarise(NonMissingGI = sum(!is.na(GlobalImprovement))) %>%
  filter(NonMissingGI >= 7) %>%
  inner_join(df2_long, by = "ID")

## Add level 2 age, gender, and PCS to the longitudinal data
df1_temporary <- df1 |>
  select(c(B_Demog_Age, B_Demog_Gender, B_Psych_PCS, ID))

df_new <- merge(df2_greaterthan7, df1_temporary, by = "ID")
```

```{r}
## lmer Analysis (GlobImp vs. AvePain_Change)
model_1 <- lmer(GlobalImprovement ~ AvePain_Change + Day + (1|ID), data = df2_greaterthan7) # Random intercept only
summary(model_1)
model_2 <- lmer(GlobalImprovement ~ AvePain_Change + Day + (Day|ID), data = df2_greaterthan7) # Random slope + Random intercept
summary(model_2)
model_3 <- lmer(GlobalImprovement ~ AvePain_Change + Mood_Change + Day + (1|ID), data = df2_greaterthan7) # Adjust AvePain_Change and Mood_Change
summary(model_3)
model_4 <- lmer(GlobalImprovement ~ AvePain_Change + Mood_Change + Day + (Day|ID), data = df2_greaterthan7) # Add random slope
summary(model_4)

## Model comparison for above analysis
anova(model_1, model_2)
anova(model_3, model_4)

## lmer Analysis (GlobImp vs. Mood_Change)
model_5 <- lmer(GlobalImprovement ~ Mood_Change + Day + (1|ID), data = df2_greaterthan7) # random intercept only
summary(model_5)
model_6 <- lmer(GlobalImprovement ~ Mood_Change + Day + (Day|ID), data = df2_greaterthan7) # Add random slope
summary(model_6)
anova(model_5, model_6) # prefer random slope + intercept
```

```{r}
model_4plus <- lmer(GlobalImprovement ~ AvePain_Change + Mood_Change + Sleep + Day + (Day|ID), 
                    data = df2_greaterthan7)
summary(model_4plus)
confint(model_4plus)
```

```{r}
model_4plus_level2 <- lmer(GlobalImprovement ~ AvePain_Change + Mood_Change + Sleep + B_Demog_Age + B_Demog_Gender + B_Psych_PCS + Day + (Day|ID), 
                    data = df_new)

model_test1 <- lmer(GlobalImprovement ~ B_Demog_Age + Day + (Day|ID), 
                    data = df_new)
summary(model_test1)

model_test2 <- lmer(GlobalImprovement ~ B_Demog_Age + AvePain_Change + Mood_Change + Sleep + Day + (Day|ID), 
                    data = df_new)
summary(model_test2)

model_test3 <- lmer(GlobalImprovement ~ B_Psych_PCS + Day + (Day|ID), 
                    data = df_new)
summary(model_test3)

model_test4 <- lmer(GlobalImprovement ~ B_Psych_PCS + AvePain_Change + Mood_Change + Sleep + Day + (Day|ID), 
                    data = df_new)
summary(model_test4)

model_test5 <- lmer(GlobalImprovement ~ Mood_Change*B_Demog_Gender + Day + (Day|ID), data = df_new)
summary(model_test5)

model_test6 <- lmer(GlobalImprovement ~ B_Demog_Gender*AvePain_Change + Day + (Day|ID),
                    data = df_new)
summary(model_test6)

model_test7 <- lmer(GlobalImprovement ~ B_Demog_Age*AvePain_Change + Day + (Day|ID),
                    data = df_new)
summary(model_test7)

model_test8 <- lmer(GlobalImprovement ~ B_Demog_Age*Mood_Change + Day + (Day|ID),
                    data = df_new)
summary(model_test8)

#### PCS * AvePain_Change ####
model_test9 <- lmer(GlobalImprovement ~ B_Psych_PCS*AvePain_Change + Day + (Day|ID),
                    data = df_new)
summary(model_test9)

model_test10 <- lmer(GlobalImprovement ~ B_Psych_PCS*Mood_Change + Day + (Day|ID),
                    data = df_new)
summary(model_test10)
```








